name: whatsapp_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  http: ^1.3.0
  intl: ^0.20.2
  firebase_messaging: ^15.2.2
  path: ^1.9.0
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.2
  flutter_contacts: ^1.1.9+2
  crypto: ^3.0.6
  permission_handler: ^11.3.1
  sqflite: ^2.4.1
  shared_preferences: ^2.5.2
  uuid: ^4.5.1
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.2
  web_socket_channel: ^3.0.2
  camera: ^0.11.1
  video_player: ^2.9.2
  emoji_picker_flutter: ^4.3.0
  camera_android: ^0.10.10
  file_picker: ^9.0.0
  path_provider: ^2.1.5
  flutter_webrtc: ^0.13.0
  wakelock_plus:
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
